name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: AudioDeviceSwitcher.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Package the plugin
      uses: SantiMA10/streamdeck-action@v0.0.1
      with:
        input-directory: "./Plugin/bin/Release/net8.0-windows"
        output-directory: "./Plugin/bin/Release"
          
    - name: Upload .streamDeckPlugin artifact
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v1.0.0
      with:
        name: com.openbyte.audiodeviceswitcher.streamDeckPlugin
        path: ./Plugin/bin/Release
        
