name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - run: pwd
    - run: ls
    - run: ls ./Plugin
    - run: ls ./Plugin/bin
    - run: ls ./Plugin/bin/${{ matrix.configuration }}
    - run: ls ./Plugin/bin/${{ matrix.configuration }}/net8.0-windows
      
    - name: Package the plugin
      uses: neilenns/streamdeck-cli-pack@v1
      with:
        path: ./Plugin/bin/${{ matrix.configuration }}/net8.0-windows
          
    - name: Upload .streamDeckPlugin artifact
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: com.openbyte.audiodeviceswitcher.streamDeckPlugin
        path: ./AudioDeviceSwitcher/Plugin/bin/${{ matrix.configuration }}
        
